agents:
  KYC:
    active: kyc_agent_v1
    versions:
      kyc_agent_v1:
        type: http
        endpoint: http://localhost:5005/agents/kyc2/decide
        timeout_ms: 1500
        enabled: true
  AML:
    active: aml_agent_v1
    versions:
      aml_agent_v1:
        type: http
        endpoint: http://localhost:5006/agents/aml2/decide
        timeout_ms: 1500
        enabled: true
  CREDIT:
    active: credit_agent_v1
    versions:
      credit_agent_v1:
        type: http
        endpoint: http://localhost:5007/agents/credit2/decide
        timeout_ms: 2000
        enabled: true
  RISK:
    active: risk_agent_v1
    versions:
      risk_agent_v1:
        type: local
        endpoint: ""
        timeout_ms: 1000
        enabled: true
